/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIndexRouteImport } from './routes/shows.index'
import { Route as BandsIndexRouteImport } from './routes/bands.index'
import { Route as ShowsNewRouteImport } from './routes/shows.new'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'
import { Route as BandsNewRouteImport } from './routes/bands.new'
import { Route as BandsSlugRouteImport } from './routes/bands.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIndexRoute = ShowsIndexRouteImport.update({
  id: '/shows/',
  path: '/shows/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsIndexRoute = BandsIndexRouteImport.update({
  id: '/bands/',
  path: '/bands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsNewRoute = ShowsNewRouteImport.update({
  id: '/shows/new',
  path: '/shows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsNewRoute = BandsNewRouteImport.update({
  id: '/bands/new',
  path: '/bands/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BandsSlugRoute = BandsSlugRouteImport.update({
  id: '/bands/$slug',
  path: '/bands/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bands/$slug': typeof BandsSlugRoute
  '/bands/new': typeof BandsNewRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/new': typeof ShowsNewRoute
  '/bands/': typeof BandsIndexRoute
  '/shows/': typeof ShowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bands/$slug': typeof BandsSlugRoute
  '/bands/new': typeof BandsNewRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/new': typeof ShowsNewRoute
  '/bands': typeof BandsIndexRoute
  '/shows': typeof ShowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feed': typeof FeedRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bands/$slug': typeof BandsSlugRoute
  '/bands/new': typeof BandsNewRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/new': typeof ShowsNewRoute
  '/bands/': typeof BandsIndexRoute
  '/shows/': typeof ShowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feed'
    | '/login'
    | '/map'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/bands/$slug'
    | '/bands/new'
    | '/shows/$id'
    | '/shows/new'
    | '/bands/'
    | '/shows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feed'
    | '/login'
    | '/map'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/bands/$slug'
    | '/bands/new'
    | '/shows/$id'
    | '/shows/new'
    | '/bands'
    | '/shows'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feed'
    | '/login'
    | '/map'
    | '/search'
    | '/signup'
    | '/sitemap.xml'
    | '/bands/$slug'
    | '/bands/new'
    | '/shows/$id'
    | '/shows/new'
    | '/bands/'
    | '/shows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FeedRoute: typeof FeedRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BandsSlugRoute: typeof BandsSlugRoute
  BandsNewRoute: typeof BandsNewRoute
  ShowsIdRoute: typeof ShowsIdRoute
  ShowsNewRoute: typeof ShowsNewRoute
  BandsIndexRoute: typeof BandsIndexRoute
  ShowsIndexRoute: typeof ShowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/': {
      id: '/shows/'
      path: '/shows'
      fullPath: '/shows/'
      preLoaderRoute: typeof ShowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands/': {
      id: '/bands/'
      path: '/bands'
      fullPath: '/bands/'
      preLoaderRoute: typeof BandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/new': {
      id: '/shows/new'
      path: '/shows/new'
      fullPath: '/shows/new'
      preLoaderRoute: typeof ShowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands/new': {
      id: '/bands/new'
      path: '/bands/new'
      fullPath: '/bands/new'
      preLoaderRoute: typeof BandsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bands/$slug': {
      id: '/bands/$slug'
      path: '/bands/$slug'
      fullPath: '/bands/$slug'
      preLoaderRoute: typeof BandsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FeedRoute: FeedRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BandsSlugRoute: BandsSlugRoute,
  BandsNewRoute: BandsNewRoute,
  ShowsIdRoute: ShowsIdRoute,
  ShowsNewRoute: ShowsNewRoute,
  BandsIndexRoute: BandsIndexRoute,
  ShowsIndexRoute: ShowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
